name: Compile Examples
on: [push, pull_request]
jobs:
 build:
   runs-on: ubuntu-latest

   strategy:
     matrix:
       fqbn:
         - arduino:avr:leonardo
         - arduino:avr:uno
         - arduino:samd:mkrwifi1010
         - arduino:samd:nano_33_iot
         - arduino:mbed:nano33ble

   steps:
     - uses: actions/checkout@master

     - uses: ArminJo/arduino-test-compile@master
       with:
         fqbn: ${{ matrix.fqbn }}
         examples-exclude: DetectingReaders