name: Compile Examples
on: [push, pull_request]
jobs:
 build:
   runs-on: ubuntu-latest

   strategy:
     matrix:
       arduino-boards-fqbn:
         - arduino:avr:leonardo
         - arduino:avr:uno
         - arduino:samd:mkrwifi1010
         - arduino:samd:nano_33_iot
         - arduino:mbed:nano33ble
         - esp8266:esp8266:huzzah:eesz=4M3M,xtal=80
         - esp32:esp32:featheresp32:FlashFreq=80
       include:
         - arduino-boards-fqbn: esp8266:esp8266:huzzah:eesz=4M3M,xtal=80
           platform-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
         - arduino-boards-fqbn: esp32:esp32:featheresp32:FlashFreq=80
           platform-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
   
     fail-fast: false
   
   steps:
     - uses: actions/checkout@master

     - uses: ArminJo/arduino-test-compile@master
       with:
         arduino-boards-fqbn: ${{ matrix.arduino-boards-fqbn }}
         platform-url: ${{ matrix.platform-url }}
         examples-exclude: DetectingReaders